#!/bin/bash

dependencies_=()
if [[ "$(uname)" == "Darwin" ]]; then
    dependencies_=(cargo.cargo.brew exa.exa.cargo bat.bat.cargo fd.fd.cargo ripgrep.rg.cargo)
else
    dependencies_=(cargo.cargo. exa.exa.cargo bat.bat.cargo fd-find.fd.cargo ripgrep.rg.cargo)
fi

installer_=""
function installer() {
    if [[ "$installer_" == "" ]]; then
        echo sudo apt $@
        sudo apt $@
    else
        echo $installer_ $@
        $installer_ $@
    fi
}

function installer_if() {
    test_cmd=$1
    if [[ "$2" != "" ]]; then
        test_cmd=$2
    fi
    test_ret=$(command -v ${test_cmd})
    if [[ "$test_ret" == "" ]]; then
        if [[ "$3" != "" ]]; then
            installer_=$3
        else
            installer_=""
        fi
        installer install $1
    fi
}

function check_dotfiles() {
    if [[ ! -d $HOME/.dotfiles ]]; then
        git clone https://github.com/caibingcheng/dotfiles.git $HOME/.dotfiles
    fi
}

function install_dependencies() {
    # installer update
    for dependency in ${dependencies_[@]}; do
        params=$(echo $dependency | awk -F'.' '{print $1" "$2" "$3}')
        installer_if $params
    done
}

function install_rcm() {
    if [[ "$(command -v rcup)" != "" ]]; then
        return 0
    fi
    if [[ "$(uname)" == "Darwin" ]]; then
        brew install rcm
    else
        sudo wget -q https://apt.thoughtbot.com/thoughtbot.gpg.key -O /etc/apt/trusted.gpg.d/thoughtbot.gpg
        echo "deb https://apt.thoughtbot.com/debian/ stable main" | sudo tee /etc/apt/sources.list.d/thoughtbot.list
        sudo apt-get update
        sudo apt-get install rcm
    fi
}

function setup_rc() {
    rcup -t rcm &&
    rcup -x LICENSE README.md setup
    if [[ "$@" != "" ]]; then
        rcup -t $@
    fi
}

function main() {
    install_rcm
    check_dotfiles
    install_dependencies
    target=$@
    if [[ "$target" == "" ]]; then
        SHELL_TYPE=$(ps -x | grep $$)
        if [[ "$(echo $SHELL_TYPE | grep zsh)" != "" ]]; then
            target=zsh
        else
            target=bash
        fi
    fi
    echo setup_rc $target
}

main $@
