#!/usr/bin/env bash
# shellcheck shell=bash

set -euo pipefail

if ! command -v docker &>/dev/null; then
    # Config docker
    for pkg in docker.io docker-doc docker-compose docker-compose-v2 podman-docker containerd runc; do
        ${SUDO} apt remove "${pkg}" -y || true
    done

    # Add Docker's official GPG key:
    ${SUDO} apt update
    ${SUDO} apt install -y ca-certificates curl
    ${SUDO} install -m 0755 -d /etc/apt/keyrings
    ${SUDO} curl -fsSL https://download.docker.com/linux/ubuntu/gpg -o /etc/apt/keyrings/docker.asc
    ${SUDO} chmod a+r /etc/apt/keyrings/docker.asc

    # Add the repository to Apt sources:
    echo \
        "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.asc] https://download.docker.com/linux/ubuntu \
        $(. /etc/os-release && echo "${VERSION_CODENAME}") stable" | \
        ${SUDO} tee /etc/apt/sources.list.d/docker.list >/dev/null
    ${SUDO} apt update
    ${SUDO} apt install -y docker-ce docker-ce-cli containerd.io docker-buildx-plugin docker-compose-plugin
    # Config docker done
fi
