#!/bin/bash

if [[ "$(command -v docker)" == "" ]]; then
  # config docker
  for pkg in docker.io docker-doc docker-compose docker-compose-v2 podman-docker containerd runc; do $SUDO apt remove $pkg -y; done
  # Add Docker's official GPG key:
  $SUDO apt update
  $SUDO apt install ca-certificates curl -y
  $SUDO install -m 0755 -d /etc/apt/keyrings
  $SUDO curl -fsSL https://download.docker.com/linux/ubuntu/gpg -o /etc/apt/keyrings/docker.asc
  $SUDO chmod a+r /etc/apt/keyrings/docker.asc

  # Add the repository to Apt sources:
  echo \
    "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.asc] https://download.docker.com/linux/ubuntu \
  $(. /etc/os-release && echo "$VERSION_CODENAME") stable" |
    $SUDO tee /etc/apt/sources.list.d/docker.list >/dev/null
  $SUDO apt update
  $SUDO apt install docker-ce docker-ce-cli containerd.io docker-buildx-plugin docker-compose-plugin -y
  # config docker done
fi
