#!/bin/bash

# max_memory_kb=$(free -k | awk '/Mem:/ {print $2}')
# max_memory_kb_80_percent=$(echo "$max_memory_kb * 0.8" | bc)
# max_memory_kb_80_percent=${max_memory_kb_80_percent%.*}

# ulimit -m $max_memory_kb_80_percent