#!/usr/bin/env bash
# shellcheck shell=bash

set -euo pipefail

# Install and setup rust development environment
if ! command -v rustup &>/dev/null; then
    curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y
    # shellcheck source=/dev/null
    source "${HOME}/.cargo/env"
    rustup component add rls rust-analysis rust-src
fi
