#!/bin/bash

# install and setup rust development environment
if [[ "$(command -v rustup)" == "" ]]; then
  curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh
  rustup component add rls rust-analysis rust-src
fi
