source ~/.cmmrc
alias sba="source ~/.bashrc && source ~/.cmmrc"

if [[ -f ~/.bash_local_rc ]]; then
    source ~/.bash_local_rc
fi

UPTIME=$(uptime | awk '{print $3}' | sed 's/,//' | xargs printf "System uptime: %s\n")
PS1='\[\033[01;33m\]$(git_branch)[$(date +"%a %T")] ${debian_chroot:+($debian_chroot):}\[\033[01;34m\]\w\[\033[01;33m\]\n\$\[\033[00m\] '
