#!/usr/bin/env bash
# shellcheck shell=bash

set -euo pipefail

TMUX_REPO="https://github.com/gpakosz/.tmux.git"

if [[ ! -d ${HOME}/.tmux ]]; then
    git clone "${TMUX_REPO}" "${HOME}/.tmux"
    ln -sf "${HOME}/.tmux/.tmux.conf" "${HOME}/.tmux.conf"
fi

ln -sf "${DOTFILES_ROOT}/tmux/tmux.conf.local" "${HOME}/.tmux.conf.local"
