#!/bin/zsh

# zsh plugins
zinit light zdharma-continuum/zinit-annex-as-monitor
zinit light zdharma-continuum/zinit-annex-bin-gem-node
zinit light zdharma-continuum/zinit-annex-patch-dl
zinit light zdharma-continuum/zinit-annex-rust

# theme
zinit ice compile'(pure|async).zsh' pick'async.zsh' src'pure.zsh'
zinit light sindresorhus/pure
PURE_PROMPT_SYMBOL='$'

zinit ice lucid wait='0'
zinit light-mode for \
zsh-users/zsh-completions

# autosuggestions
zinit ice lucid wait='0'
zinit light zsh-users/zsh-autosuggestions
ZSH_AUTOSUGGEST_BUFFER_MAX_SIZE=64

zinit ice lucid wait='0'
zinit light zdharma-continuum/fast-syntax-highlighting

# omz plugin
zinit ice lucid wait='0'
zinit snippet OMZ::plugins/sudo/sudo.plugin.zsh
