#!/bin/bash

alias sba=". ~/.bash_profile"
alias crc="test -f "$(command -v code)" && code ~/.dotfiles || vim ~/.dotfiles"
alias dotfiles="${HOME}/.dotfiles/bootstrap"

alias ssh="autossh"
alias ntpon="timedatectl set-ntp yes"
alias ntpoff="timedatectl set-ntp no"

alias gb="git branch"
alias gba="git branch -a"
alias gss="git status"
alias gssu="git status --untracked-files=no"
alias gll="git log"
alias gaa="git add ."
alias gmm="git commit"
alias gma="git commit -a"
alias gmd="git commit --amend"
alias gdd="git diff"
alias gdt="git difftool"
alias gpl="git pull"
alias gsu="git submodule update --init"
alias gcf="git clean -fd"

alias gits="git multi"
alias gsb="gits branch"
alias gsba="gits branch -a"
alias gsss="gits status"
alias gsssu="gits status --untracked-files=no"
alias gsll="gits log"
alias gsdd="gits diff"

test -f "$(command -v exa)" && alias ls="exa"
test -f "$(command -v fdfind)" && alias fd="fdfind -I"
test -f "$(command -v batcat)" && alias bat="batcat"
alias ll="ls -lh"
alias la="ls -lha"
alias cls="clear"
alias c="code ."
alias line="wc -l"
alias word="wc -w"
alias byte="wc -c"
alias bat="bat --color=always"
alias mmem="top -b -o +%MEM | head -n 20"
alias mm="make -j$(nproc)"

alias tt="tldr"
alias rr="ranger"
# ff alias for thefuck
# ll alias for ls -lh
# mm alias for make
alias gg="gitui"
alias pp="tgpt"

test -f "$(command -v fzf)" && eval "$(fzf --bash)"
test -f "$(command -v zoxide)" && eval "$(zoxide init bash)"
test -f "$(command -v zoxide)" || alias z="cd"
test -f "$(command -v thefuck)" && eval $(thefuck --alias ff)

alias cd-="cd -"
alias cd..="cd .."
alias z-="z -"
alias z..="z .."
alias ..="z .."
alias ...="z .."
alias ....="z ../.."

alias zc='zc__() { cur__=$(pwd) && echo "$@" && z "$@" && code . && z ${cur__}; } && zc__'
