#!/bin/bash
# keep ~/.bashrc clean and put all your custom commands here

alias sba=". ~/.bashrc"
eval "$(fzf --bash)"
eval "$(zoxide init bash)"
test "$(command -v pipx)" != "" && eval "$(register-python-argcomplete3 pipx)"

if [[ -f ~/.git-completion.bash ]]; then
    . ~/.git-completion.bash
fi

if [[ -f ~/.cmmrc ]]; then
    . ~/.cmmrc
fi

# specitial features
if [[ -f ~/.bash_local_rc ]]; then
    . ~/.bash_local_rc
fi
